/*
websocket-gateway

Testing ShellAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package qovery-ws

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/qovery/qovery-client-ws-go"
)

func Test_qovery-ws_ShellAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShellAPIService HandleShellExec", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var organization string
		var cluster string
		var project string
		var environment string
		var service string
		var podName string
		var containerName string
		var command []string
		var ttyWidth int32
		var ttyHeight int32

		resp, httpRes, err := apiClient.ShellAPI.HandleShellExec(context.Background(), organization, cluster, project, environment, service, podName, containerName, command, ttyWidth, ttyHeight).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
