/*
websocket-gateway

Testing RemoteDebugAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package qovery-ws

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/qovery/qovery-client-ws-go"
)

func Test_qovery-ws_RemoteDebugAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RemoteDebugAPIService HandleShellRemoteDebug", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var organization string
		var cluster string
		var flavor DebugFlavor
		var ttyWidth int32
		var ttyHeight int32
		var nodeSelector string

		resp, httpRes, err := apiClient.RemoteDebugAPI.HandleShellRemoteDebug(context.Background(), organization, cluster, flavor, ttyWidth, ttyHeight, nodeSelector).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
