/*
websocket-gateway

Describe the weboscket endpoints

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NodeTaintDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeTaintDto{}

// NodeTaintDto struct for NodeTaintDto
type NodeTaintDto struct {
	Effect string `json:"effect"`
	Key string `json:"key"`
	Value string `json:"value"`
}

type _NodeTaintDto NodeTaintDto

// NewNodeTaintDto instantiates a new NodeTaintDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeTaintDto(effect string, key string, value string) *NodeTaintDto {
	this := NodeTaintDto{}
	this.Effect = effect
	this.Key = key
	this.Value = value
	return &this
}

// NewNodeTaintDtoWithDefaults instantiates a new NodeTaintDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeTaintDtoWithDefaults() *NodeTaintDto {
	this := NodeTaintDto{}
	return &this
}

// GetEffect returns the Effect field value
func (o *NodeTaintDto) GetEffect() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Effect
}

// GetEffectOk returns a tuple with the Effect field value
// and a boolean to check if the value has been set.
func (o *NodeTaintDto) GetEffectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Effect, true
}

// SetEffect sets field value
func (o *NodeTaintDto) SetEffect(v string) {
	o.Effect = v
}

// GetKey returns the Key field value
func (o *NodeTaintDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *NodeTaintDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *NodeTaintDto) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *NodeTaintDto) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NodeTaintDto) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *NodeTaintDto) SetValue(v string) {
	o.Value = v
}

func (o NodeTaintDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeTaintDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["effect"] = o.Effect
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *NodeTaintDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"effect",
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodeTaintDto := _NodeTaintDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodeTaintDto)

	if err != nil {
		return err
	}

	*o = NodeTaintDto(varNodeTaintDto)

	return err
}

type NullableNodeTaintDto struct {
	value *NodeTaintDto
	isSet bool
}

func (v NullableNodeTaintDto) Get() *NodeTaintDto {
	return v.value
}

func (v *NullableNodeTaintDto) Set(val *NodeTaintDto) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeTaintDto) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeTaintDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeTaintDto(val *NodeTaintDto) *NullableNodeTaintDto {
	return &NullableNodeTaintDto{value: val, isSet: true}
}

func (v NullableNodeTaintDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeTaintDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


