/*
websocket-gateway

Describe the weboscket endpoints

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
)

// ServiceInfraLogResponseDto struct for ServiceInfraLogResponseDto
type ServiceInfraLogResponseDto struct {
	CreatedAt NullableInt32 `json:"created_at,omitempty"`
	Message string `json:"message"`
}

// NewServiceInfraLogResponseDto instantiates a new ServiceInfraLogResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInfraLogResponseDto(message string) *ServiceInfraLogResponseDto {
	this := ServiceInfraLogResponseDto{}
	this.Message = message
	return &this
}

// NewServiceInfraLogResponseDtoWithDefaults instantiates a new ServiceInfraLogResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInfraLogResponseDtoWithDefaults() *ServiceInfraLogResponseDto {
	this := ServiceInfraLogResponseDto{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceInfraLogResponseDto) GetCreatedAt() int32 {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret int32
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceInfraLogResponseDto) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ServiceInfraLogResponseDto) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableInt32 and assigns it to the CreatedAt field.
func (o *ServiceInfraLogResponseDto) SetCreatedAt(v int32) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *ServiceInfraLogResponseDto) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *ServiceInfraLogResponseDto) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetMessage returns the Message field value
func (o *ServiceInfraLogResponseDto) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ServiceInfraLogResponseDto) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ServiceInfraLogResponseDto) SetMessage(v string) {
	o.Message = v
}

func (o ServiceInfraLogResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if true {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableServiceInfraLogResponseDto struct {
	value *ServiceInfraLogResponseDto
	isSet bool
}

func (v NullableServiceInfraLogResponseDto) Get() *ServiceInfraLogResponseDto {
	return v.value
}

func (v *NullableServiceInfraLogResponseDto) Set(val *ServiceInfraLogResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInfraLogResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInfraLogResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInfraLogResponseDto(val *ServiceInfraLogResponseDto) *NullableServiceInfraLogResponseDto {
	return &NullableServiceInfraLogResponseDto{value: val, isSet: true}
}

func (v NullableServiceInfraLogResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInfraLogResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


