/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterListNodesResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterListNodesResponseDto{}

// ClusterListNodesResponseDto struct for ClusterListNodesResponseDto
type ClusterListNodesResponseDto struct {
	Nodes []NodeDto `json:"nodes"`
}

type _ClusterListNodesResponseDto ClusterListNodesResponseDto

// NewClusterListNodesResponseDto instantiates a new ClusterListNodesResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterListNodesResponseDto(nodes []NodeDto) *ClusterListNodesResponseDto {
	this := ClusterListNodesResponseDto{}
	this.Nodes = nodes
	return &this
}

// NewClusterListNodesResponseDtoWithDefaults instantiates a new ClusterListNodesResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterListNodesResponseDtoWithDefaults() *ClusterListNodesResponseDto {
	this := ClusterListNodesResponseDto{}
	return &this
}

// GetNodes returns the Nodes field value
func (o *ClusterListNodesResponseDto) GetNodes() []NodeDto {
	if o == nil {
		var ret []NodeDto
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *ClusterListNodesResponseDto) GetNodesOk() ([]NodeDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *ClusterListNodesResponseDto) SetNodes(v []NodeDto) {
	o.Nodes = v
}

func (o ClusterListNodesResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterListNodesResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodes"] = o.Nodes
	return toSerialize, nil
}

func (o *ClusterListNodesResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nodes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterListNodesResponseDto := _ClusterListNodesResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterListNodesResponseDto)

	if err != nil {
		return err
	}

	*o = ClusterListNodesResponseDto(varClusterListNodesResponseDto)

	return err
}

type NullableClusterListNodesResponseDto struct {
	value *ClusterListNodesResponseDto
	isSet bool
}

func (v NullableClusterListNodesResponseDto) Get() *ClusterListNodesResponseDto {
	return v.value
}

func (v *NullableClusterListNodesResponseDto) Set(val *ClusterListNodesResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterListNodesResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterListNodesResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterListNodesResponseDto(val *ClusterListNodesResponseDto) *NullableClusterListNodesResponseDto {
	return &NullableClusterListNodesResponseDto{value: val, isSet: true}
}

func (v NullableClusterListNodesResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterListNodesResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


