/*
websocket-gateway

Describe the weboscket endpoints

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
)

// checks if the ClusterStatusDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterStatusDto{}

// ClusterStatusDto struct for ClusterStatusDto
type ClusterStatusDto struct {
	Nodes []ClusterNodeDto `json:"nodes"`
}

// NewClusterStatusDto instantiates a new ClusterStatusDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterStatusDto(nodes []ClusterNodeDto) *ClusterStatusDto {
	this := ClusterStatusDto{}
	this.Nodes = nodes
	return &this
}

// NewClusterStatusDtoWithDefaults instantiates a new ClusterStatusDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterStatusDtoWithDefaults() *ClusterStatusDto {
	this := ClusterStatusDto{}
	return &this
}

// GetNodes returns the Nodes field value
func (o *ClusterStatusDto) GetNodes() []ClusterNodeDto {
	if o == nil {
		var ret []ClusterNodeDto
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *ClusterStatusDto) GetNodesOk() ([]ClusterNodeDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *ClusterStatusDto) SetNodes(v []ClusterNodeDto) {
	o.Nodes = v
}

func (o ClusterStatusDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterStatusDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodes"] = o.Nodes
	return toSerialize, nil
}

type NullableClusterStatusDto struct {
	value *ClusterStatusDto
	isSet bool
}

func (v NullableClusterStatusDto) Get() *ClusterStatusDto {
	return v.value
}

func (v *NullableClusterStatusDto) Set(val *ClusterStatusDto) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterStatusDto) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterStatusDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterStatusDto(val *ClusterStatusDto) *NullableClusterStatusDto {
	return &NullableClusterStatusDto{value: val, isSet: true}
}

func (v NullableClusterStatusDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterStatusDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


