/*
websocket-gateway

Describe the weboscket endpoints

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QoveryPodInErrorComponentInFailure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QoveryPodInErrorComponentInFailure{}

// QoveryPodInErrorComponentInFailure struct for QoveryPodInErrorComponentInFailure
type QoveryPodInErrorComponentInFailure struct {
	ComponentName string `json:"component_name"`
	PodName string `json:"pod_name"`
	ContainerName string `json:"container_name"`
	Level *string `json:"level,omitempty"`
	Reason NullableString `json:"reason,omitempty"`
	Message NullableString `json:"message,omitempty"`
}

type _QoveryPodInErrorComponentInFailure QoveryPodInErrorComponentInFailure

// NewQoveryPodInErrorComponentInFailure instantiates a new QoveryPodInErrorComponentInFailure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQoveryPodInErrorComponentInFailure(componentName string, podName string, containerName string) *QoveryPodInErrorComponentInFailure {
	this := QoveryPodInErrorComponentInFailure{}
	this.ComponentName = componentName
	this.PodName = podName
	this.ContainerName = containerName
	return &this
}

// NewQoveryPodInErrorComponentInFailureWithDefaults instantiates a new QoveryPodInErrorComponentInFailure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQoveryPodInErrorComponentInFailureWithDefaults() *QoveryPodInErrorComponentInFailure {
	this := QoveryPodInErrorComponentInFailure{}
	return &this
}

// GetComponentName returns the ComponentName field value
func (o *QoveryPodInErrorComponentInFailure) GetComponentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentName
}

// GetComponentNameOk returns a tuple with the ComponentName field value
// and a boolean to check if the value has been set.
func (o *QoveryPodInErrorComponentInFailure) GetComponentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentName, true
}

// SetComponentName sets field value
func (o *QoveryPodInErrorComponentInFailure) SetComponentName(v string) {
	o.ComponentName = v
}

// GetPodName returns the PodName field value
func (o *QoveryPodInErrorComponentInFailure) GetPodName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PodName
}

// GetPodNameOk returns a tuple with the PodName field value
// and a boolean to check if the value has been set.
func (o *QoveryPodInErrorComponentInFailure) GetPodNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PodName, true
}

// SetPodName sets field value
func (o *QoveryPodInErrorComponentInFailure) SetPodName(v string) {
	o.PodName = v
}

// GetContainerName returns the ContainerName field value
func (o *QoveryPodInErrorComponentInFailure) GetContainerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerName
}

// GetContainerNameOk returns a tuple with the ContainerName field value
// and a boolean to check if the value has been set.
func (o *QoveryPodInErrorComponentInFailure) GetContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerName, true
}

// SetContainerName sets field value
func (o *QoveryPodInErrorComponentInFailure) SetContainerName(v string) {
	o.ContainerName = v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *QoveryPodInErrorComponentInFailure) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QoveryPodInErrorComponentInFailure) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *QoveryPodInErrorComponentInFailure) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *QoveryPodInErrorComponentInFailure) SetLevel(v string) {
	o.Level = &v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QoveryPodInErrorComponentInFailure) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QoveryPodInErrorComponentInFailure) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *QoveryPodInErrorComponentInFailure) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *QoveryPodInErrorComponentInFailure) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *QoveryPodInErrorComponentInFailure) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *QoveryPodInErrorComponentInFailure) UnsetReason() {
	o.Reason.Unset()
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QoveryPodInErrorComponentInFailure) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QoveryPodInErrorComponentInFailure) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *QoveryPodInErrorComponentInFailure) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *QoveryPodInErrorComponentInFailure) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *QoveryPodInErrorComponentInFailure) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *QoveryPodInErrorComponentInFailure) UnsetMessage() {
	o.Message.Unset()
}

func (o QoveryPodInErrorComponentInFailure) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QoveryPodInErrorComponentInFailure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["component_name"] = o.ComponentName
	toSerialize["pod_name"] = o.PodName
	toSerialize["container_name"] = o.ContainerName
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return toSerialize, nil
}

func (o *QoveryPodInErrorComponentInFailure) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"component_name",
		"pod_name",
		"container_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQoveryPodInErrorComponentInFailure := _QoveryPodInErrorComponentInFailure{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQoveryPodInErrorComponentInFailure)

	if err != nil {
		return err
	}

	*o = QoveryPodInErrorComponentInFailure(varQoveryPodInErrorComponentInFailure)

	return err
}

type NullableQoveryPodInErrorComponentInFailure struct {
	value *QoveryPodInErrorComponentInFailure
	isSet bool
}

func (v NullableQoveryPodInErrorComponentInFailure) Get() *QoveryPodInErrorComponentInFailure {
	return v.value
}

func (v *NullableQoveryPodInErrorComponentInFailure) Set(val *QoveryPodInErrorComponentInFailure) {
	v.value = val
	v.isSet = true
}

func (v NullableQoveryPodInErrorComponentInFailure) IsSet() bool {
	return v.isSet
}

func (v *NullableQoveryPodInErrorComponentInFailure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQoveryPodInErrorComponentInFailure(val *QoveryPodInErrorComponentInFailure) *NullableQoveryPodInErrorComponentInFailure {
	return &NullableQoveryPodInErrorComponentInFailure{value: val, isSet: true}
}

func (v NullableQoveryPodInErrorComponentInFailure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQoveryPodInErrorComponentInFailure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


