/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArgocdAppStatusDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArgocdAppStatusDto{}

// ArgocdAppStatusDto struct for ArgocdAppStatusDto
type ArgocdAppStatusDto struct {
	Id string `json:"id"`
	Pods []PodStatusDto `json:"pods"`
	State ServiceStateDto `json:"state"`
}

type _ArgocdAppStatusDto ArgocdAppStatusDto

// NewArgocdAppStatusDto instantiates a new ArgocdAppStatusDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArgocdAppStatusDto(id string, pods []PodStatusDto, state ServiceStateDto) *ArgocdAppStatusDto {
	this := ArgocdAppStatusDto{}
	this.Id = id
	this.Pods = pods
	this.State = state
	return &this
}

// NewArgocdAppStatusDtoWithDefaults instantiates a new ArgocdAppStatusDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArgocdAppStatusDtoWithDefaults() *ArgocdAppStatusDto {
	this := ArgocdAppStatusDto{}
	return &this
}

// GetId returns the Id field value
func (o *ArgocdAppStatusDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ArgocdAppStatusDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ArgocdAppStatusDto) SetId(v string) {
	o.Id = v
}

// GetPods returns the Pods field value
func (o *ArgocdAppStatusDto) GetPods() []PodStatusDto {
	if o == nil {
		var ret []PodStatusDto
		return ret
	}

	return o.Pods
}

// GetPodsOk returns a tuple with the Pods field value
// and a boolean to check if the value has been set.
func (o *ArgocdAppStatusDto) GetPodsOk() ([]PodStatusDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pods, true
}

// SetPods sets field value
func (o *ArgocdAppStatusDto) SetPods(v []PodStatusDto) {
	o.Pods = v
}

// GetState returns the State field value
func (o *ArgocdAppStatusDto) GetState() ServiceStateDto {
	if o == nil {
		var ret ServiceStateDto
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ArgocdAppStatusDto) GetStateOk() (*ServiceStateDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ArgocdAppStatusDto) SetState(v ServiceStateDto) {
	o.State = v
}

func (o ArgocdAppStatusDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArgocdAppStatusDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["pods"] = o.Pods
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *ArgocdAppStatusDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"pods",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArgocdAppStatusDto := _ArgocdAppStatusDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArgocdAppStatusDto)

	if err != nil {
		return err
	}

	*o = ArgocdAppStatusDto(varArgocdAppStatusDto)

	return err
}

type NullableArgocdAppStatusDto struct {
	value *ArgocdAppStatusDto
	isSet bool
}

func (v NullableArgocdAppStatusDto) Get() *ArgocdAppStatusDto {
	return v.value
}

func (v *NullableArgocdAppStatusDto) Set(val *ArgocdAppStatusDto) {
	v.value = val
	v.isSet = true
}

func (v NullableArgocdAppStatusDto) IsSet() bool {
	return v.isSet
}

func (v *NullableArgocdAppStatusDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArgocdAppStatusDto(val *ArgocdAppStatusDto) *NullableArgocdAppStatusDto {
	return &NullableArgocdAppStatusDto{value: val, isSet: true}
}

func (v NullableArgocdAppStatusDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArgocdAppStatusDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


