/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterQuotaWarningDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterQuotaWarningDto{}

// ClusterQuotaWarningDto struct for ClusterQuotaWarningDto
type ClusterQuotaWarningDto struct {
	DetectedAt int64 `json:"detected_at"`
	LastSeenAt int64 `json:"last_seen_at"`
	Message string `json:"message"`
	Provider string `json:"provider"`
	QuotaCode string `json:"quota_code"`
	QuotaName NullableString `json:"quota_name,omitempty"`
	Region NullableString `json:"region,omitempty"`
	Resource NullableString `json:"resource,omitempty"`
	Source string `json:"source"`
	Status string `json:"status"`
	SuggestedAction string `json:"suggested_action"`
}

type _ClusterQuotaWarningDto ClusterQuotaWarningDto

// NewClusterQuotaWarningDto instantiates a new ClusterQuotaWarningDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterQuotaWarningDto(detectedAt int64, lastSeenAt int64, message string, provider string, quotaCode string, source string, status string, suggestedAction string) *ClusterQuotaWarningDto {
	this := ClusterQuotaWarningDto{}
	this.DetectedAt = detectedAt
	this.LastSeenAt = lastSeenAt
	this.Message = message
	this.Provider = provider
	this.QuotaCode = quotaCode
	this.Source = source
	this.Status = status
	this.SuggestedAction = suggestedAction
	return &this
}

// NewClusterQuotaWarningDtoWithDefaults instantiates a new ClusterQuotaWarningDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterQuotaWarningDtoWithDefaults() *ClusterQuotaWarningDto {
	this := ClusterQuotaWarningDto{}
	return &this
}

// GetDetectedAt returns the DetectedAt field value
func (o *ClusterQuotaWarningDto) GetDetectedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DetectedAt
}

// GetDetectedAtOk returns a tuple with the DetectedAt field value
// and a boolean to check if the value has been set.
func (o *ClusterQuotaWarningDto) GetDetectedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DetectedAt, true
}

// SetDetectedAt sets field value
func (o *ClusterQuotaWarningDto) SetDetectedAt(v int64) {
	o.DetectedAt = v
}

// GetLastSeenAt returns the LastSeenAt field value
func (o *ClusterQuotaWarningDto) GetLastSeenAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LastSeenAt
}

// GetLastSeenAtOk returns a tuple with the LastSeenAt field value
// and a boolean to check if the value has been set.
func (o *ClusterQuotaWarningDto) GetLastSeenAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastSeenAt, true
}

// SetLastSeenAt sets field value
func (o *ClusterQuotaWarningDto) SetLastSeenAt(v int64) {
	o.LastSeenAt = v
}

// GetMessage returns the Message field value
func (o *ClusterQuotaWarningDto) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ClusterQuotaWarningDto) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ClusterQuotaWarningDto) SetMessage(v string) {
	o.Message = v
}

// GetProvider returns the Provider field value
func (o *ClusterQuotaWarningDto) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ClusterQuotaWarningDto) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ClusterQuotaWarningDto) SetProvider(v string) {
	o.Provider = v
}

// GetQuotaCode returns the QuotaCode field value
func (o *ClusterQuotaWarningDto) GetQuotaCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuotaCode
}

// GetQuotaCodeOk returns a tuple with the QuotaCode field value
// and a boolean to check if the value has been set.
func (o *ClusterQuotaWarningDto) GetQuotaCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuotaCode, true
}

// SetQuotaCode sets field value
func (o *ClusterQuotaWarningDto) SetQuotaCode(v string) {
	o.QuotaCode = v
}

// GetQuotaName returns the QuotaName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterQuotaWarningDto) GetQuotaName() string {
	if o == nil || IsNil(o.QuotaName.Get()) {
		var ret string
		return ret
	}
	return *o.QuotaName.Get()
}

// GetQuotaNameOk returns a tuple with the QuotaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterQuotaWarningDto) GetQuotaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QuotaName.Get(), o.QuotaName.IsSet()
}

// HasQuotaName returns a boolean if a field has been set.
func (o *ClusterQuotaWarningDto) HasQuotaName() bool {
	if o != nil && o.QuotaName.IsSet() {
		return true
	}

	return false
}

// SetQuotaName gets a reference to the given NullableString and assigns it to the QuotaName field.
func (o *ClusterQuotaWarningDto) SetQuotaName(v string) {
	o.QuotaName.Set(&v)
}
// SetQuotaNameNil sets the value for QuotaName to be an explicit nil
func (o *ClusterQuotaWarningDto) SetQuotaNameNil() {
	o.QuotaName.Set(nil)
}

// UnsetQuotaName ensures that no value is present for QuotaName, not even an explicit nil
func (o *ClusterQuotaWarningDto) UnsetQuotaName() {
	o.QuotaName.Unset()
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterQuotaWarningDto) GetRegion() string {
	if o == nil || IsNil(o.Region.Get()) {
		var ret string
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterQuotaWarningDto) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *ClusterQuotaWarningDto) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableString and assigns it to the Region field.
func (o *ClusterQuotaWarningDto) SetRegion(v string) {
	o.Region.Set(&v)
}
// SetRegionNil sets the value for Region to be an explicit nil
func (o *ClusterQuotaWarningDto) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *ClusterQuotaWarningDto) UnsetRegion() {
	o.Region.Unset()
}

// GetResource returns the Resource field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterQuotaWarningDto) GetResource() string {
	if o == nil || IsNil(o.Resource.Get()) {
		var ret string
		return ret
	}
	return *o.Resource.Get()
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterQuotaWarningDto) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Resource.Get(), o.Resource.IsSet()
}

// HasResource returns a boolean if a field has been set.
func (o *ClusterQuotaWarningDto) HasResource() bool {
	if o != nil && o.Resource.IsSet() {
		return true
	}

	return false
}

// SetResource gets a reference to the given NullableString and assigns it to the Resource field.
func (o *ClusterQuotaWarningDto) SetResource(v string) {
	o.Resource.Set(&v)
}
// SetResourceNil sets the value for Resource to be an explicit nil
func (o *ClusterQuotaWarningDto) SetResourceNil() {
	o.Resource.Set(nil)
}

// UnsetResource ensures that no value is present for Resource, not even an explicit nil
func (o *ClusterQuotaWarningDto) UnsetResource() {
	o.Resource.Unset()
}

// GetSource returns the Source field value
func (o *ClusterQuotaWarningDto) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ClusterQuotaWarningDto) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ClusterQuotaWarningDto) SetSource(v string) {
	o.Source = v
}

// GetStatus returns the Status field value
func (o *ClusterQuotaWarningDto) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ClusterQuotaWarningDto) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ClusterQuotaWarningDto) SetStatus(v string) {
	o.Status = v
}

// GetSuggestedAction returns the SuggestedAction field value
func (o *ClusterQuotaWarningDto) GetSuggestedAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SuggestedAction
}

// GetSuggestedActionOk returns a tuple with the SuggestedAction field value
// and a boolean to check if the value has been set.
func (o *ClusterQuotaWarningDto) GetSuggestedActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuggestedAction, true
}

// SetSuggestedAction sets field value
func (o *ClusterQuotaWarningDto) SetSuggestedAction(v string) {
	o.SuggestedAction = v
}

func (o ClusterQuotaWarningDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterQuotaWarningDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["detected_at"] = o.DetectedAt
	toSerialize["last_seen_at"] = o.LastSeenAt
	toSerialize["message"] = o.Message
	toSerialize["provider"] = o.Provider
	toSerialize["quota_code"] = o.QuotaCode
	if o.QuotaName.IsSet() {
		toSerialize["quota_name"] = o.QuotaName.Get()
	}
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.Resource.IsSet() {
		toSerialize["resource"] = o.Resource.Get()
	}
	toSerialize["source"] = o.Source
	toSerialize["status"] = o.Status
	toSerialize["suggested_action"] = o.SuggestedAction
	return toSerialize, nil
}

func (o *ClusterQuotaWarningDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"detected_at",
		"last_seen_at",
		"message",
		"provider",
		"quota_code",
		"source",
		"status",
		"suggested_action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterQuotaWarningDto := _ClusterQuotaWarningDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterQuotaWarningDto)

	if err != nil {
		return err
	}

	*o = ClusterQuotaWarningDto(varClusterQuotaWarningDto)

	return err
}

type NullableClusterQuotaWarningDto struct {
	value *ClusterQuotaWarningDto
	isSet bool
}

func (v NullableClusterQuotaWarningDto) Get() *ClusterQuotaWarningDto {
	return v.value
}

func (v *NullableClusterQuotaWarningDto) Set(val *ClusterQuotaWarningDto) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterQuotaWarningDto) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterQuotaWarningDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterQuotaWarningDto(val *ClusterQuotaWarningDto) *NullableClusterQuotaWarningDto {
	return &NullableClusterQuotaWarningDto{value: val, isSet: true}
}

func (v NullableClusterQuotaWarningDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterQuotaWarningDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


