/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterStatusDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterStatusDto{}

// ClusterStatusDto struct for ClusterStatusDto
type ClusterStatusDto struct {
	ComputedStatus ClusterComputedStatusDto `json:"computed_status"`
	NodePools []NodePoolInfoDto `json:"node_pools"`
	Nodes []ClusterNodeDto `json:"nodes"`
	Pvcs []PvcInfoDto `json:"pvcs"`
}

type _ClusterStatusDto ClusterStatusDto

// NewClusterStatusDto instantiates a new ClusterStatusDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterStatusDto(computedStatus ClusterComputedStatusDto, nodePools []NodePoolInfoDto, nodes []ClusterNodeDto, pvcs []PvcInfoDto) *ClusterStatusDto {
	this := ClusterStatusDto{}
	this.ComputedStatus = computedStatus
	this.NodePools = nodePools
	this.Nodes = nodes
	this.Pvcs = pvcs
	return &this
}

// NewClusterStatusDtoWithDefaults instantiates a new ClusterStatusDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterStatusDtoWithDefaults() *ClusterStatusDto {
	this := ClusterStatusDto{}
	return &this
}

// GetComputedStatus returns the ComputedStatus field value
func (o *ClusterStatusDto) GetComputedStatus() ClusterComputedStatusDto {
	if o == nil {
		var ret ClusterComputedStatusDto
		return ret
	}

	return o.ComputedStatus
}

// GetComputedStatusOk returns a tuple with the ComputedStatus field value
// and a boolean to check if the value has been set.
func (o *ClusterStatusDto) GetComputedStatusOk() (*ClusterComputedStatusDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComputedStatus, true
}

// SetComputedStatus sets field value
func (o *ClusterStatusDto) SetComputedStatus(v ClusterComputedStatusDto) {
	o.ComputedStatus = v
}

// GetNodePools returns the NodePools field value
func (o *ClusterStatusDto) GetNodePools() []NodePoolInfoDto {
	if o == nil {
		var ret []NodePoolInfoDto
		return ret
	}

	return o.NodePools
}

// GetNodePoolsOk returns a tuple with the NodePools field value
// and a boolean to check if the value has been set.
func (o *ClusterStatusDto) GetNodePoolsOk() ([]NodePoolInfoDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.NodePools, true
}

// SetNodePools sets field value
func (o *ClusterStatusDto) SetNodePools(v []NodePoolInfoDto) {
	o.NodePools = v
}

// GetNodes returns the Nodes field value
func (o *ClusterStatusDto) GetNodes() []ClusterNodeDto {
	if o == nil {
		var ret []ClusterNodeDto
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *ClusterStatusDto) GetNodesOk() ([]ClusterNodeDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *ClusterStatusDto) SetNodes(v []ClusterNodeDto) {
	o.Nodes = v
}

// GetPvcs returns the Pvcs field value
func (o *ClusterStatusDto) GetPvcs() []PvcInfoDto {
	if o == nil {
		var ret []PvcInfoDto
		return ret
	}

	return o.Pvcs
}

// GetPvcsOk returns a tuple with the Pvcs field value
// and a boolean to check if the value has been set.
func (o *ClusterStatusDto) GetPvcsOk() ([]PvcInfoDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pvcs, true
}

// SetPvcs sets field value
func (o *ClusterStatusDto) SetPvcs(v []PvcInfoDto) {
	o.Pvcs = v
}

func (o ClusterStatusDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterStatusDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["computed_status"] = o.ComputedStatus
	toSerialize["node_pools"] = o.NodePools
	toSerialize["nodes"] = o.Nodes
	toSerialize["pvcs"] = o.Pvcs
	return toSerialize, nil
}

func (o *ClusterStatusDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"computed_status",
		"node_pools",
		"nodes",
		"pvcs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterStatusDto := _ClusterStatusDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterStatusDto)

	if err != nil {
		return err
	}

	*o = ClusterStatusDto(varClusterStatusDto)

	return err
}

type NullableClusterStatusDto struct {
	value *ClusterStatusDto
	isSet bool
}

func (v NullableClusterStatusDto) Get() *ClusterStatusDto {
	return v.value
}

func (v *NullableClusterStatusDto) Set(val *ClusterStatusDto) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterStatusDto) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterStatusDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterStatusDto(val *ClusterStatusDto) *NullableClusterStatusDto {
	return &NullableClusterStatusDto{value: val, isSet: true}
}

func (v NullableClusterStatusDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterStatusDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


