/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QoveryComponentInFailureOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QoveryComponentInFailureOneOf{}

// QoveryComponentInFailureOneOf struct for QoveryComponentInFailureOneOf
type QoveryComponentInFailureOneOf struct {
	POD_IN_ERROR QoveryComponentInFailureOneOfPODINERROR `json:"POD_IN_ERROR"`
}

type _QoveryComponentInFailureOneOf QoveryComponentInFailureOneOf

// NewQoveryComponentInFailureOneOf instantiates a new QoveryComponentInFailureOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQoveryComponentInFailureOneOf(pODINERROR QoveryComponentInFailureOneOfPODINERROR) *QoveryComponentInFailureOneOf {
	this := QoveryComponentInFailureOneOf{}
	this.POD_IN_ERROR = pODINERROR
	return &this
}

// NewQoveryComponentInFailureOneOfWithDefaults instantiates a new QoveryComponentInFailureOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQoveryComponentInFailureOneOfWithDefaults() *QoveryComponentInFailureOneOf {
	this := QoveryComponentInFailureOneOf{}
	return &this
}

// GetPOD_IN_ERROR returns the POD_IN_ERROR field value
func (o *QoveryComponentInFailureOneOf) GetPOD_IN_ERROR() QoveryComponentInFailureOneOfPODINERROR {
	if o == nil {
		var ret QoveryComponentInFailureOneOfPODINERROR
		return ret
	}

	return o.POD_IN_ERROR
}

// GetPOD_IN_ERROROk returns a tuple with the POD_IN_ERROR field value
// and a boolean to check if the value has been set.
func (o *QoveryComponentInFailureOneOf) GetPOD_IN_ERROROk() (*QoveryComponentInFailureOneOfPODINERROR, bool) {
	if o == nil {
		return nil, false
	}
	return &o.POD_IN_ERROR, true
}

// SetPOD_IN_ERROR sets field value
func (o *QoveryComponentInFailureOneOf) SetPOD_IN_ERROR(v QoveryComponentInFailureOneOfPODINERROR) {
	o.POD_IN_ERROR = v
}

func (o QoveryComponentInFailureOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QoveryComponentInFailureOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["POD_IN_ERROR"] = o.POD_IN_ERROR
	return toSerialize, nil
}

func (o *QoveryComponentInFailureOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"POD_IN_ERROR",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQoveryComponentInFailureOneOf := _QoveryComponentInFailureOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQoveryComponentInFailureOneOf)

	if err != nil {
		return err
	}

	*o = QoveryComponentInFailureOneOf(varQoveryComponentInFailureOneOf)

	return err
}

type NullableQoveryComponentInFailureOneOf struct {
	value *QoveryComponentInFailureOneOf
	isSet bool
}

func (v NullableQoveryComponentInFailureOneOf) Get() *QoveryComponentInFailureOneOf {
	return v.value
}

func (v *NullableQoveryComponentInFailureOneOf) Set(val *QoveryComponentInFailureOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableQoveryComponentInFailureOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableQoveryComponentInFailureOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQoveryComponentInFailureOneOf(val *QoveryComponentInFailureOneOf) *NullableQoveryComponentInFailureOneOf {
	return &NullableQoveryComponentInFailureOneOf{value: val, isSet: true}
}

func (v NullableQoveryComponentInFailureOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQoveryComponentInFailureOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


