/*
websocket-gateway

Describe the weboscket endpoints

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
)

// ServiceLogResponseDto struct for ServiceLogResponseDto
type ServiceLogResponseDto struct {
	CreatedAt NullableInt32 `json:"created_at,omitempty"`
	Message string `json:"message"`
	PodName string `json:"pod_name"`
	Version string `json:"version"`
}

// NewServiceLogResponseDto instantiates a new ServiceLogResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceLogResponseDto(message string, podName string, version string) *ServiceLogResponseDto {
	this := ServiceLogResponseDto{}
	this.Message = message
	this.PodName = podName
	this.Version = version
	return &this
}

// NewServiceLogResponseDtoWithDefaults instantiates a new ServiceLogResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceLogResponseDtoWithDefaults() *ServiceLogResponseDto {
	this := ServiceLogResponseDto{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceLogResponseDto) GetCreatedAt() int32 {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret int32
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceLogResponseDto) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ServiceLogResponseDto) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableInt32 and assigns it to the CreatedAt field.
func (o *ServiceLogResponseDto) SetCreatedAt(v int32) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *ServiceLogResponseDto) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *ServiceLogResponseDto) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetMessage returns the Message field value
func (o *ServiceLogResponseDto) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ServiceLogResponseDto) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ServiceLogResponseDto) SetMessage(v string) {
	o.Message = v
}

// GetPodName returns the PodName field value
func (o *ServiceLogResponseDto) GetPodName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PodName
}

// GetPodNameOk returns a tuple with the PodName field value
// and a boolean to check if the value has been set.
func (o *ServiceLogResponseDto) GetPodNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PodName, true
}

// SetPodName sets field value
func (o *ServiceLogResponseDto) SetPodName(v string) {
	o.PodName = v
}

// GetVersion returns the Version field value
func (o *ServiceLogResponseDto) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ServiceLogResponseDto) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ServiceLogResponseDto) SetVersion(v string) {
	o.Version = v
}

func (o ServiceLogResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if true {
		toSerialize["message"] = o.Message
	}
	if true {
		toSerialize["pod_name"] = o.PodName
	}
	if true {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableServiceLogResponseDto struct {
	value *ServiceLogResponseDto
	isSet bool
}

func (v NullableServiceLogResponseDto) Get() *ServiceLogResponseDto {
	return v.value
}

func (v *NullableServiceLogResponseDto) Set(val *ServiceLogResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceLogResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceLogResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceLogResponseDto(val *ServiceLogResponseDto) *NullableServiceLogResponseDto {
	return &NullableServiceLogResponseDto{value: val, isSet: true}
}

func (v NullableServiceLogResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceLogResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


