/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QoveryNodeFailure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QoveryNodeFailure{}

// QoveryNodeFailure struct for QoveryNodeFailure
type QoveryNodeFailure struct {
	Message string `json:"message"`
	NodeAttributes QoveryNodeAttributes `json:"node_attributes"`
	Reason string `json:"reason"`
	Type string `json:"type"`
}

type _QoveryNodeFailure QoveryNodeFailure

// NewQoveryNodeFailure instantiates a new QoveryNodeFailure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQoveryNodeFailure(message string, nodeAttributes QoveryNodeAttributes, reason string, type_ string) *QoveryNodeFailure {
	this := QoveryNodeFailure{}
	this.Message = message
	this.NodeAttributes = nodeAttributes
	this.Reason = reason
	this.Type = type_
	return &this
}

// NewQoveryNodeFailureWithDefaults instantiates a new QoveryNodeFailure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQoveryNodeFailureWithDefaults() *QoveryNodeFailure {
	this := QoveryNodeFailure{}
	return &this
}

// GetMessage returns the Message field value
func (o *QoveryNodeFailure) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *QoveryNodeFailure) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *QoveryNodeFailure) SetMessage(v string) {
	o.Message = v
}

// GetNodeAttributes returns the NodeAttributes field value
func (o *QoveryNodeFailure) GetNodeAttributes() QoveryNodeAttributes {
	if o == nil {
		var ret QoveryNodeAttributes
		return ret
	}

	return o.NodeAttributes
}

// GetNodeAttributesOk returns a tuple with the NodeAttributes field value
// and a boolean to check if the value has been set.
func (o *QoveryNodeFailure) GetNodeAttributesOk() (*QoveryNodeAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeAttributes, true
}

// SetNodeAttributes sets field value
func (o *QoveryNodeFailure) SetNodeAttributes(v QoveryNodeAttributes) {
	o.NodeAttributes = v
}

// GetReason returns the Reason field value
func (o *QoveryNodeFailure) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *QoveryNodeFailure) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *QoveryNodeFailure) SetReason(v string) {
	o.Reason = v
}

// GetType returns the Type field value
func (o *QoveryNodeFailure) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QoveryNodeFailure) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QoveryNodeFailure) SetType(v string) {
	o.Type = v
}

func (o QoveryNodeFailure) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QoveryNodeFailure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["node_attributes"] = o.NodeAttributes
	toSerialize["reason"] = o.Reason
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *QoveryNodeFailure) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"node_attributes",
		"reason",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQoveryNodeFailure := _QoveryNodeFailure{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQoveryNodeFailure)

	if err != nil {
		return err
	}

	*o = QoveryNodeFailure(varQoveryNodeFailure)

	return err
}

type NullableQoveryNodeFailure struct {
	value *QoveryNodeFailure
	isSet bool
}

func (v NullableQoveryNodeFailure) Get() *QoveryNodeFailure {
	return v.value
}

func (v *NullableQoveryNodeFailure) Set(val *QoveryNodeFailure) {
	v.value = val
	v.isSet = true
}

func (v NullableQoveryNodeFailure) IsSet() bool {
	return v.isSet
}

func (v *NullableQoveryNodeFailure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQoveryNodeFailure(val *QoveryNodeFailure) *NullableQoveryNodeFailure {
	return &NullableQoveryNodeFailure{value: val, isSet: true}
}

func (v NullableQoveryNodeFailure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQoveryNodeFailure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


