/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CertificateStatusDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateStatusDto{}

// CertificateStatusDto struct for CertificateStatusDto
type CertificateStatusDto struct {
	DnsNames []string `json:"dns_names"`
	FailedIssuanceAttemptCount int64 `json:"failed_issuance_attempt_count"`
	LastFailureIssuanceTime NullableInt64 `json:"last_failure_issuance_time,omitempty"`
	NotAfter int64 `json:"not_after"`
	NotBefore int64 `json:"not_before"`
	RenewalTime int64 `json:"renewal_time"`
	State ServiceStateDto `json:"state"`
	StateMessage NullableString `json:"state_message,omitempty"`
}

type _CertificateStatusDto CertificateStatusDto

// NewCertificateStatusDto instantiates a new CertificateStatusDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateStatusDto(dnsNames []string, failedIssuanceAttemptCount int64, notAfter int64, notBefore int64, renewalTime int64, state ServiceStateDto) *CertificateStatusDto {
	this := CertificateStatusDto{}
	this.DnsNames = dnsNames
	this.FailedIssuanceAttemptCount = failedIssuanceAttemptCount
	this.NotAfter = notAfter
	this.NotBefore = notBefore
	this.RenewalTime = renewalTime
	this.State = state
	return &this
}

// NewCertificateStatusDtoWithDefaults instantiates a new CertificateStatusDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateStatusDtoWithDefaults() *CertificateStatusDto {
	this := CertificateStatusDto{}
	return &this
}

// GetDnsNames returns the DnsNames field value
func (o *CertificateStatusDto) GetDnsNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DnsNames
}

// GetDnsNamesOk returns a tuple with the DnsNames field value
// and a boolean to check if the value has been set.
func (o *CertificateStatusDto) GetDnsNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DnsNames, true
}

// SetDnsNames sets field value
func (o *CertificateStatusDto) SetDnsNames(v []string) {
	o.DnsNames = v
}

// GetFailedIssuanceAttemptCount returns the FailedIssuanceAttemptCount field value
func (o *CertificateStatusDto) GetFailedIssuanceAttemptCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FailedIssuanceAttemptCount
}

// GetFailedIssuanceAttemptCountOk returns a tuple with the FailedIssuanceAttemptCount field value
// and a boolean to check if the value has been set.
func (o *CertificateStatusDto) GetFailedIssuanceAttemptCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedIssuanceAttemptCount, true
}

// SetFailedIssuanceAttemptCount sets field value
func (o *CertificateStatusDto) SetFailedIssuanceAttemptCount(v int64) {
	o.FailedIssuanceAttemptCount = v
}

// GetLastFailureIssuanceTime returns the LastFailureIssuanceTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificateStatusDto) GetLastFailureIssuanceTime() int64 {
	if o == nil || IsNil(o.LastFailureIssuanceTime.Get()) {
		var ret int64
		return ret
	}
	return *o.LastFailureIssuanceTime.Get()
}

// GetLastFailureIssuanceTimeOk returns a tuple with the LastFailureIssuanceTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificateStatusDto) GetLastFailureIssuanceTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastFailureIssuanceTime.Get(), o.LastFailureIssuanceTime.IsSet()
}

// HasLastFailureIssuanceTime returns a boolean if a field has been set.
func (o *CertificateStatusDto) HasLastFailureIssuanceTime() bool {
	if o != nil && o.LastFailureIssuanceTime.IsSet() {
		return true
	}

	return false
}

// SetLastFailureIssuanceTime gets a reference to the given NullableInt64 and assigns it to the LastFailureIssuanceTime field.
func (o *CertificateStatusDto) SetLastFailureIssuanceTime(v int64) {
	o.LastFailureIssuanceTime.Set(&v)
}
// SetLastFailureIssuanceTimeNil sets the value for LastFailureIssuanceTime to be an explicit nil
func (o *CertificateStatusDto) SetLastFailureIssuanceTimeNil() {
	o.LastFailureIssuanceTime.Set(nil)
}

// UnsetLastFailureIssuanceTime ensures that no value is present for LastFailureIssuanceTime, not even an explicit nil
func (o *CertificateStatusDto) UnsetLastFailureIssuanceTime() {
	o.LastFailureIssuanceTime.Unset()
}

// GetNotAfter returns the NotAfter field value
func (o *CertificateStatusDto) GetNotAfter() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NotAfter
}

// GetNotAfterOk returns a tuple with the NotAfter field value
// and a boolean to check if the value has been set.
func (o *CertificateStatusDto) GetNotAfterOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotAfter, true
}

// SetNotAfter sets field value
func (o *CertificateStatusDto) SetNotAfter(v int64) {
	o.NotAfter = v
}

// GetNotBefore returns the NotBefore field value
func (o *CertificateStatusDto) GetNotBefore() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NotBefore
}

// GetNotBeforeOk returns a tuple with the NotBefore field value
// and a boolean to check if the value has been set.
func (o *CertificateStatusDto) GetNotBeforeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotBefore, true
}

// SetNotBefore sets field value
func (o *CertificateStatusDto) SetNotBefore(v int64) {
	o.NotBefore = v
}

// GetRenewalTime returns the RenewalTime field value
func (o *CertificateStatusDto) GetRenewalTime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RenewalTime
}

// GetRenewalTimeOk returns a tuple with the RenewalTime field value
// and a boolean to check if the value has been set.
func (o *CertificateStatusDto) GetRenewalTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RenewalTime, true
}

// SetRenewalTime sets field value
func (o *CertificateStatusDto) SetRenewalTime(v int64) {
	o.RenewalTime = v
}

// GetState returns the State field value
func (o *CertificateStatusDto) GetState() ServiceStateDto {
	if o == nil {
		var ret ServiceStateDto
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CertificateStatusDto) GetStateOk() (*ServiceStateDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CertificateStatusDto) SetState(v ServiceStateDto) {
	o.State = v
}

// GetStateMessage returns the StateMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificateStatusDto) GetStateMessage() string {
	if o == nil || IsNil(o.StateMessage.Get()) {
		var ret string
		return ret
	}
	return *o.StateMessage.Get()
}

// GetStateMessageOk returns a tuple with the StateMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificateStatusDto) GetStateMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StateMessage.Get(), o.StateMessage.IsSet()
}

// HasStateMessage returns a boolean if a field has been set.
func (o *CertificateStatusDto) HasStateMessage() bool {
	if o != nil && o.StateMessage.IsSet() {
		return true
	}

	return false
}

// SetStateMessage gets a reference to the given NullableString and assigns it to the StateMessage field.
func (o *CertificateStatusDto) SetStateMessage(v string) {
	o.StateMessage.Set(&v)
}
// SetStateMessageNil sets the value for StateMessage to be an explicit nil
func (o *CertificateStatusDto) SetStateMessageNil() {
	o.StateMessage.Set(nil)
}

// UnsetStateMessage ensures that no value is present for StateMessage, not even an explicit nil
func (o *CertificateStatusDto) UnsetStateMessage() {
	o.StateMessage.Unset()
}

func (o CertificateStatusDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateStatusDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dns_names"] = o.DnsNames
	toSerialize["failed_issuance_attempt_count"] = o.FailedIssuanceAttemptCount
	if o.LastFailureIssuanceTime.IsSet() {
		toSerialize["last_failure_issuance_time"] = o.LastFailureIssuanceTime.Get()
	}
	toSerialize["not_after"] = o.NotAfter
	toSerialize["not_before"] = o.NotBefore
	toSerialize["renewal_time"] = o.RenewalTime
	toSerialize["state"] = o.State
	if o.StateMessage.IsSet() {
		toSerialize["state_message"] = o.StateMessage.Get()
	}
	return toSerialize, nil
}

func (o *CertificateStatusDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dns_names",
		"failed_issuance_attempt_count",
		"not_after",
		"not_before",
		"renewal_time",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateStatusDto := _CertificateStatusDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCertificateStatusDto)

	if err != nil {
		return err
	}

	*o = CertificateStatusDto(varCertificateStatusDto)

	return err
}

type NullableCertificateStatusDto struct {
	value *CertificateStatusDto
	isSet bool
}

func (v NullableCertificateStatusDto) Get() *CertificateStatusDto {
	return v.value
}

func (v *NullableCertificateStatusDto) Set(val *CertificateStatusDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateStatusDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateStatusDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateStatusDto(val *CertificateStatusDto) *NullableCertificateStatusDto {
	return &NullableCertificateStatusDto{value: val, isSet: true}
}

func (v NullableCertificateStatusDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateStatusDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


