/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QoveryClusterKubeVersionStatusOneOf1Drift type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QoveryClusterKubeVersionStatusOneOf1Drift{}

// QoveryClusterKubeVersionStatusOneOf1Drift struct for QoveryClusterKubeVersionStatusOneOf1Drift
type QoveryClusterKubeVersionStatusOneOf1Drift struct {
	ExpectedKubeVersion string `json:"expected_kube_version"`
	KubeVersion string `json:"kube_version"`
}

type _QoveryClusterKubeVersionStatusOneOf1Drift QoveryClusterKubeVersionStatusOneOf1Drift

// NewQoveryClusterKubeVersionStatusOneOf1Drift instantiates a new QoveryClusterKubeVersionStatusOneOf1Drift object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQoveryClusterKubeVersionStatusOneOf1Drift(expectedKubeVersion string, kubeVersion string) *QoveryClusterKubeVersionStatusOneOf1Drift {
	this := QoveryClusterKubeVersionStatusOneOf1Drift{}
	this.ExpectedKubeVersion = expectedKubeVersion
	this.KubeVersion = kubeVersion
	return &this
}

// NewQoveryClusterKubeVersionStatusOneOf1DriftWithDefaults instantiates a new QoveryClusterKubeVersionStatusOneOf1Drift object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQoveryClusterKubeVersionStatusOneOf1DriftWithDefaults() *QoveryClusterKubeVersionStatusOneOf1Drift {
	this := QoveryClusterKubeVersionStatusOneOf1Drift{}
	return &this
}

// GetExpectedKubeVersion returns the ExpectedKubeVersion field value
func (o *QoveryClusterKubeVersionStatusOneOf1Drift) GetExpectedKubeVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedKubeVersion
}

// GetExpectedKubeVersionOk returns a tuple with the ExpectedKubeVersion field value
// and a boolean to check if the value has been set.
func (o *QoveryClusterKubeVersionStatusOneOf1Drift) GetExpectedKubeVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedKubeVersion, true
}

// SetExpectedKubeVersion sets field value
func (o *QoveryClusterKubeVersionStatusOneOf1Drift) SetExpectedKubeVersion(v string) {
	o.ExpectedKubeVersion = v
}

// GetKubeVersion returns the KubeVersion field value
func (o *QoveryClusterKubeVersionStatusOneOf1Drift) GetKubeVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KubeVersion
}

// GetKubeVersionOk returns a tuple with the KubeVersion field value
// and a boolean to check if the value has been set.
func (o *QoveryClusterKubeVersionStatusOneOf1Drift) GetKubeVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KubeVersion, true
}

// SetKubeVersion sets field value
func (o *QoveryClusterKubeVersionStatusOneOf1Drift) SetKubeVersion(v string) {
	o.KubeVersion = v
}

func (o QoveryClusterKubeVersionStatusOneOf1Drift) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QoveryClusterKubeVersionStatusOneOf1Drift) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expected_kube_version"] = o.ExpectedKubeVersion
	toSerialize["kube_version"] = o.KubeVersion
	return toSerialize, nil
}

func (o *QoveryClusterKubeVersionStatusOneOf1Drift) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expected_kube_version",
		"kube_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQoveryClusterKubeVersionStatusOneOf1Drift := _QoveryClusterKubeVersionStatusOneOf1Drift{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQoveryClusterKubeVersionStatusOneOf1Drift)

	if err != nil {
		return err
	}

	*o = QoveryClusterKubeVersionStatusOneOf1Drift(varQoveryClusterKubeVersionStatusOneOf1Drift)

	return err
}

type NullableQoveryClusterKubeVersionStatusOneOf1Drift struct {
	value *QoveryClusterKubeVersionStatusOneOf1Drift
	isSet bool
}

func (v NullableQoveryClusterKubeVersionStatusOneOf1Drift) Get() *QoveryClusterKubeVersionStatusOneOf1Drift {
	return v.value
}

func (v *NullableQoveryClusterKubeVersionStatusOneOf1Drift) Set(val *QoveryClusterKubeVersionStatusOneOf1Drift) {
	v.value = val
	v.isSet = true
}

func (v NullableQoveryClusterKubeVersionStatusOneOf1Drift) IsSet() bool {
	return v.isSet
}

func (v *NullableQoveryClusterKubeVersionStatusOneOf1Drift) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQoveryClusterKubeVersionStatusOneOf1Drift(val *QoveryClusterKubeVersionStatusOneOf1Drift) *NullableQoveryClusterKubeVersionStatusOneOf1Drift {
	return &NullableQoveryClusterKubeVersionStatusOneOf1Drift{value: val, isSet: true}
}

func (v NullableQoveryClusterKubeVersionStatusOneOf1Drift) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQoveryClusterKubeVersionStatusOneOf1Drift) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


