/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceActionDetailsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceActionDetailsDto{}

// ServiceActionDetailsDto struct for ServiceActionDetailsDto
type ServiceActionDetailsDto struct {
	Action ServiceActionDto `json:"action"`
	SubAction ServiceSubActionDto `json:"sub_action"`
}

type _ServiceActionDetailsDto ServiceActionDetailsDto

// NewServiceActionDetailsDto instantiates a new ServiceActionDetailsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceActionDetailsDto(action ServiceActionDto, subAction ServiceSubActionDto) *ServiceActionDetailsDto {
	this := ServiceActionDetailsDto{}
	this.Action = action
	this.SubAction = subAction
	return &this
}

// NewServiceActionDetailsDtoWithDefaults instantiates a new ServiceActionDetailsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceActionDetailsDtoWithDefaults() *ServiceActionDetailsDto {
	this := ServiceActionDetailsDto{}
	return &this
}

// GetAction returns the Action field value
func (o *ServiceActionDetailsDto) GetAction() ServiceActionDto {
	if o == nil {
		var ret ServiceActionDto
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ServiceActionDetailsDto) GetActionOk() (*ServiceActionDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ServiceActionDetailsDto) SetAction(v ServiceActionDto) {
	o.Action = v
}

// GetSubAction returns the SubAction field value
func (o *ServiceActionDetailsDto) GetSubAction() ServiceSubActionDto {
	if o == nil {
		var ret ServiceSubActionDto
		return ret
	}

	return o.SubAction
}

// GetSubActionOk returns a tuple with the SubAction field value
// and a boolean to check if the value has been set.
func (o *ServiceActionDetailsDto) GetSubActionOk() (*ServiceSubActionDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubAction, true
}

// SetSubAction sets field value
func (o *ServiceActionDetailsDto) SetSubAction(v ServiceSubActionDto) {
	o.SubAction = v
}

func (o ServiceActionDetailsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceActionDetailsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["sub_action"] = o.SubAction
	return toSerialize, nil
}

func (o *ServiceActionDetailsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"sub_action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceActionDetailsDto := _ServiceActionDetailsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceActionDetailsDto)

	if err != nil {
		return err
	}

	*o = ServiceActionDetailsDto(varServiceActionDetailsDto)

	return err
}

type NullableServiceActionDetailsDto struct {
	value *ServiceActionDetailsDto
	isSet bool
}

func (v NullableServiceActionDetailsDto) Get() *ServiceActionDetailsDto {
	return v.value
}

func (v *NullableServiceActionDetailsDto) Set(val *ServiceActionDetailsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceActionDetailsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceActionDetailsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceActionDetailsDto(val *ServiceActionDetailsDto) *NullableServiceActionDetailsDto {
	return &NullableServiceActionDetailsDto{value: val, isSet: true}
}

func (v NullableServiceActionDetailsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceActionDetailsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


