/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TerraformStatusDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerraformStatusDto{}

// TerraformStatusDto struct for TerraformStatusDto
type TerraformStatusDto struct {
	Id string `json:"id"`
	Pods []PodStatusDto `json:"pods"`
	State ServiceStateDto `json:"state"`
	TriggeredAction ServiceActionDetailsDto `json:"triggered_action"`
}

type _TerraformStatusDto TerraformStatusDto

// NewTerraformStatusDto instantiates a new TerraformStatusDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerraformStatusDto(id string, pods []PodStatusDto, state ServiceStateDto, triggeredAction ServiceActionDetailsDto) *TerraformStatusDto {
	this := TerraformStatusDto{}
	this.Id = id
	this.Pods = pods
	this.State = state
	this.TriggeredAction = triggeredAction
	return &this
}

// NewTerraformStatusDtoWithDefaults instantiates a new TerraformStatusDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerraformStatusDtoWithDefaults() *TerraformStatusDto {
	this := TerraformStatusDto{}
	return &this
}

// GetId returns the Id field value
func (o *TerraformStatusDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TerraformStatusDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TerraformStatusDto) SetId(v string) {
	o.Id = v
}

// GetPods returns the Pods field value
func (o *TerraformStatusDto) GetPods() []PodStatusDto {
	if o == nil {
		var ret []PodStatusDto
		return ret
	}

	return o.Pods
}

// GetPodsOk returns a tuple with the Pods field value
// and a boolean to check if the value has been set.
func (o *TerraformStatusDto) GetPodsOk() ([]PodStatusDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pods, true
}

// SetPods sets field value
func (o *TerraformStatusDto) SetPods(v []PodStatusDto) {
	o.Pods = v
}

// GetState returns the State field value
func (o *TerraformStatusDto) GetState() ServiceStateDto {
	if o == nil {
		var ret ServiceStateDto
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *TerraformStatusDto) GetStateOk() (*ServiceStateDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *TerraformStatusDto) SetState(v ServiceStateDto) {
	o.State = v
}

// GetTriggeredAction returns the TriggeredAction field value
func (o *TerraformStatusDto) GetTriggeredAction() ServiceActionDetailsDto {
	if o == nil {
		var ret ServiceActionDetailsDto
		return ret
	}

	return o.TriggeredAction
}

// GetTriggeredActionOk returns a tuple with the TriggeredAction field value
// and a boolean to check if the value has been set.
func (o *TerraformStatusDto) GetTriggeredActionOk() (*ServiceActionDetailsDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TriggeredAction, true
}

// SetTriggeredAction sets field value
func (o *TerraformStatusDto) SetTriggeredAction(v ServiceActionDetailsDto) {
	o.TriggeredAction = v
}

func (o TerraformStatusDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerraformStatusDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["pods"] = o.Pods
	toSerialize["state"] = o.State
	toSerialize["triggered_action"] = o.TriggeredAction
	return toSerialize, nil
}

func (o *TerraformStatusDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"pods",
		"state",
		"triggered_action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTerraformStatusDto := _TerraformStatusDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTerraformStatusDto)

	if err != nil {
		return err
	}

	*o = TerraformStatusDto(varTerraformStatusDto)

	return err
}

type NullableTerraformStatusDto struct {
	value *TerraformStatusDto
	isSet bool
}

func (v NullableTerraformStatusDto) Get() *TerraformStatusDto {
	return v.value
}

func (v *NullableTerraformStatusDto) Set(val *TerraformStatusDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTerraformStatusDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTerraformStatusDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerraformStatusDto(val *TerraformStatusDto) *NullableTerraformStatusDto {
	return &NullableTerraformStatusDto{value: val, isSet: true}
}

func (v NullableTerraformStatusDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerraformStatusDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


