/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"fmt"
)

// QoveryClusterKubeVersionStatus - struct for QoveryClusterKubeVersionStatus
type QoveryClusterKubeVersionStatus struct {
	KubeVersionStatusDriftValue *KubeVersionStatusDriftValue
	KubeVersionStatusOkValue *KubeVersionStatusOkValue
	KubeVersionStatusUnknownValue *KubeVersionStatusUnknownValue
}

// KubeVersionStatusDriftValueAsQoveryClusterKubeVersionStatus is a convenience function that returns KubeVersionStatusDriftValue wrapped in QoveryClusterKubeVersionStatus
func KubeVersionStatusDriftValueAsQoveryClusterKubeVersionStatus(v *KubeVersionStatusDriftValue) QoveryClusterKubeVersionStatus {
	return QoveryClusterKubeVersionStatus{
		KubeVersionStatusDriftValue: v,
	}
}

// KubeVersionStatusOkValueAsQoveryClusterKubeVersionStatus is a convenience function that returns KubeVersionStatusOkValue wrapped in QoveryClusterKubeVersionStatus
func KubeVersionStatusOkValueAsQoveryClusterKubeVersionStatus(v *KubeVersionStatusOkValue) QoveryClusterKubeVersionStatus {
	return QoveryClusterKubeVersionStatus{
		KubeVersionStatusOkValue: v,
	}
}

// KubeVersionStatusUnknownValueAsQoveryClusterKubeVersionStatus is a convenience function that returns KubeVersionStatusUnknownValue wrapped in QoveryClusterKubeVersionStatus
func KubeVersionStatusUnknownValueAsQoveryClusterKubeVersionStatus(v *KubeVersionStatusUnknownValue) QoveryClusterKubeVersionStatus {
	return QoveryClusterKubeVersionStatus{
		KubeVersionStatusUnknownValue: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *QoveryClusterKubeVersionStatus) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into KubeVersionStatusDriftValue
	err = newStrictDecoder(data).Decode(&dst.KubeVersionStatusDriftValue)
	if err == nil {
		jsonKubeVersionStatusDriftValue, _ := json.Marshal(dst.KubeVersionStatusDriftValue)
		if string(jsonKubeVersionStatusDriftValue) == "{}" { // empty struct
			dst.KubeVersionStatusDriftValue = nil
		} else {
			match++
		}
	} else {
		dst.KubeVersionStatusDriftValue = nil
	}

	// try to unmarshal data into KubeVersionStatusOkValue
	err = newStrictDecoder(data).Decode(&dst.KubeVersionStatusOkValue)
	if err == nil {
		jsonKubeVersionStatusOkValue, _ := json.Marshal(dst.KubeVersionStatusOkValue)
		if string(jsonKubeVersionStatusOkValue) == "{}" { // empty struct
			dst.KubeVersionStatusOkValue = nil
		} else {
			match++
		}
	} else {
		dst.KubeVersionStatusOkValue = nil
	}

	// try to unmarshal data into KubeVersionStatusUnknownValue
	err = newStrictDecoder(data).Decode(&dst.KubeVersionStatusUnknownValue)
	if err == nil {
		jsonKubeVersionStatusUnknownValue, _ := json.Marshal(dst.KubeVersionStatusUnknownValue)
		if string(jsonKubeVersionStatusUnknownValue) == "{}" { // empty struct
			dst.KubeVersionStatusUnknownValue = nil
		} else {
			match++
		}
	} else {
		dst.KubeVersionStatusUnknownValue = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.KubeVersionStatusDriftValue = nil
		dst.KubeVersionStatusOkValue = nil
		dst.KubeVersionStatusUnknownValue = nil

		return fmt.Errorf("data matches more than one schema in oneOf(QoveryClusterKubeVersionStatus)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(QoveryClusterKubeVersionStatus)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src QoveryClusterKubeVersionStatus) MarshalJSON() ([]byte, error) {
	if src.KubeVersionStatusDriftValue != nil {
		return json.Marshal(&src.KubeVersionStatusDriftValue)
	}

	if src.KubeVersionStatusOkValue != nil {
		return json.Marshal(&src.KubeVersionStatusOkValue)
	}

	if src.KubeVersionStatusUnknownValue != nil {
		return json.Marshal(&src.KubeVersionStatusUnknownValue)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *QoveryClusterKubeVersionStatus) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.KubeVersionStatusDriftValue != nil {
		return obj.KubeVersionStatusDriftValue
	}

	if obj.KubeVersionStatusOkValue != nil {
		return obj.KubeVersionStatusOkValue
	}

	if obj.KubeVersionStatusUnknownValue != nil {
		return obj.KubeVersionStatusUnknownValue
	}

	// all schemas are nil
	return nil
}

type NullableQoveryClusterKubeVersionStatus struct {
	value *QoveryClusterKubeVersionStatus
	isSet bool
}

func (v NullableQoveryClusterKubeVersionStatus) Get() *QoveryClusterKubeVersionStatus {
	return v.value
}

func (v *NullableQoveryClusterKubeVersionStatus) Set(val *QoveryClusterKubeVersionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableQoveryClusterKubeVersionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableQoveryClusterKubeVersionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQoveryClusterKubeVersionStatus(val *QoveryClusterKubeVersionStatus) *NullableQoveryClusterKubeVersionStatus {
	return &NullableQoveryClusterKubeVersionStatus{value: val, isSet: true}
}

func (v NullableQoveryClusterKubeVersionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQoveryClusterKubeVersionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


