/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlueprintServiceCreatedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintServiceCreatedEvent{}

// BlueprintServiceCreatedEvent One blueprint service-created event. The stream emits these until the connection closes.
type BlueprintServiceCreatedEvent struct {
	// Id of the blueprint whose service was created.
	BlueprintId string `json:"blueprint_id"`
}

type _BlueprintServiceCreatedEvent BlueprintServiceCreatedEvent

// NewBlueprintServiceCreatedEvent instantiates a new BlueprintServiceCreatedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintServiceCreatedEvent(blueprintId string) *BlueprintServiceCreatedEvent {
	this := BlueprintServiceCreatedEvent{}
	this.BlueprintId = blueprintId
	return &this
}

// NewBlueprintServiceCreatedEventWithDefaults instantiates a new BlueprintServiceCreatedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintServiceCreatedEventWithDefaults() *BlueprintServiceCreatedEvent {
	this := BlueprintServiceCreatedEvent{}
	return &this
}

// GetBlueprintId returns the BlueprintId field value
func (o *BlueprintServiceCreatedEvent) GetBlueprintId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlueprintId
}

// GetBlueprintIdOk returns a tuple with the BlueprintId field value
// and a boolean to check if the value has been set.
func (o *BlueprintServiceCreatedEvent) GetBlueprintIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlueprintId, true
}

// SetBlueprintId sets field value
func (o *BlueprintServiceCreatedEvent) SetBlueprintId(v string) {
	o.BlueprintId = v
}

func (o BlueprintServiceCreatedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintServiceCreatedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["blueprint_id"] = o.BlueprintId
	return toSerialize, nil
}

func (o *BlueprintServiceCreatedEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"blueprint_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlueprintServiceCreatedEvent := _BlueprintServiceCreatedEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlueprintServiceCreatedEvent)

	if err != nil {
		return err
	}

	*o = BlueprintServiceCreatedEvent(varBlueprintServiceCreatedEvent)

	return err
}

type NullableBlueprintServiceCreatedEvent struct {
	value *BlueprintServiceCreatedEvent
	isSet bool
}

func (v NullableBlueprintServiceCreatedEvent) Get() *BlueprintServiceCreatedEvent {
	return v.value
}

func (v *NullableBlueprintServiceCreatedEvent) Set(val *BlueprintServiceCreatedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintServiceCreatedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintServiceCreatedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintServiceCreatedEvent(val *BlueprintServiceCreatedEvent) *NullableBlueprintServiceCreatedEvent {
	return &NullableBlueprintServiceCreatedEvent{value: val, isSet: true}
}

func (v NullableBlueprintServiceCreatedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintServiceCreatedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


