/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScaledObjectConditionDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScaledObjectConditionDto{}

// ScaledObjectConditionDto struct for ScaledObjectConditionDto
type ScaledObjectConditionDto struct {
	Message NullableString `json:"message,omitempty"`
	Reason NullableString `json:"reason,omitempty"`
	Status string `json:"status"`
	Type string `json:"type"`
}

type _ScaledObjectConditionDto ScaledObjectConditionDto

// NewScaledObjectConditionDto instantiates a new ScaledObjectConditionDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScaledObjectConditionDto(status string, type_ string) *ScaledObjectConditionDto {
	this := ScaledObjectConditionDto{}
	this.Status = status
	this.Type = type_
	return &this
}

// NewScaledObjectConditionDtoWithDefaults instantiates a new ScaledObjectConditionDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScaledObjectConditionDtoWithDefaults() *ScaledObjectConditionDto {
	this := ScaledObjectConditionDto{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScaledObjectConditionDto) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScaledObjectConditionDto) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *ScaledObjectConditionDto) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *ScaledObjectConditionDto) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *ScaledObjectConditionDto) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *ScaledObjectConditionDto) UnsetMessage() {
	o.Message.Unset()
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScaledObjectConditionDto) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScaledObjectConditionDto) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *ScaledObjectConditionDto) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *ScaledObjectConditionDto) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *ScaledObjectConditionDto) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *ScaledObjectConditionDto) UnsetReason() {
	o.Reason.Unset()
}

// GetStatus returns the Status field value
func (o *ScaledObjectConditionDto) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ScaledObjectConditionDto) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ScaledObjectConditionDto) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *ScaledObjectConditionDto) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ScaledObjectConditionDto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ScaledObjectConditionDto) SetType(v string) {
	o.Type = v
}

func (o ScaledObjectConditionDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScaledObjectConditionDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ScaledObjectConditionDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScaledObjectConditionDto := _ScaledObjectConditionDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScaledObjectConditionDto)

	if err != nil {
		return err
	}

	*o = ScaledObjectConditionDto(varScaledObjectConditionDto)

	return err
}

type NullableScaledObjectConditionDto struct {
	value *ScaledObjectConditionDto
	isSet bool
}

func (v NullableScaledObjectConditionDto) Get() *ScaledObjectConditionDto {
	return v.value
}

func (v *NullableScaledObjectConditionDto) Set(val *ScaledObjectConditionDto) {
	v.value = val
	v.isSet = true
}

func (v NullableScaledObjectConditionDto) IsSet() bool {
	return v.isSet
}

func (v *NullableScaledObjectConditionDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScaledObjectConditionDto(val *ScaledObjectConditionDto) *NullableScaledObjectConditionDto {
	return &NullableScaledObjectConditionDto{value: val, isSet: true}
}

func (v NullableScaledObjectConditionDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScaledObjectConditionDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


