/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PodInfoDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PodInfoDto{}

// PodInfoDto struct for PodInfoDto
type PodInfoDto struct {
	CpuMilliLimit NullableInt32 `json:"cpu_milli_limit,omitempty"`
	CpuMilliRequest NullableInt32 `json:"cpu_milli_request,omitempty"`
	CreatedAt int64 `json:"created_at"`
	ErrorContainerStatuses []NodePodErrorStatusDto `json:"error_container_statuses"`
	ImagesVersion map[string]string `json:"images_version"`
	MemoryMibLimit NullableInt32 `json:"memory_mib_limit,omitempty"`
	MemoryMibRequest NullableInt32 `json:"memory_mib_request,omitempty"`
	MetricsUsage MetricsUsageDto `json:"metrics_usage"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
	RestartCount int32 `json:"restart_count"`
}

type _PodInfoDto PodInfoDto

// NewPodInfoDto instantiates a new PodInfoDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPodInfoDto(createdAt int64, errorContainerStatuses []NodePodErrorStatusDto, imagesVersion map[string]string, metricsUsage MetricsUsageDto, name string, namespace string, restartCount int32) *PodInfoDto {
	this := PodInfoDto{}
	this.CreatedAt = createdAt
	this.ErrorContainerStatuses = errorContainerStatuses
	this.ImagesVersion = imagesVersion
	this.MetricsUsage = metricsUsage
	this.Name = name
	this.Namespace = namespace
	this.RestartCount = restartCount
	return &this
}

// NewPodInfoDtoWithDefaults instantiates a new PodInfoDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPodInfoDtoWithDefaults() *PodInfoDto {
	this := PodInfoDto{}
	return &this
}

// GetCpuMilliLimit returns the CpuMilliLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PodInfoDto) GetCpuMilliLimit() int32 {
	if o == nil || IsNil(o.CpuMilliLimit.Get()) {
		var ret int32
		return ret
	}
	return *o.CpuMilliLimit.Get()
}

// GetCpuMilliLimitOk returns a tuple with the CpuMilliLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PodInfoDto) GetCpuMilliLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CpuMilliLimit.Get(), o.CpuMilliLimit.IsSet()
}

// HasCpuMilliLimit returns a boolean if a field has been set.
func (o *PodInfoDto) HasCpuMilliLimit() bool {
	if o != nil && o.CpuMilliLimit.IsSet() {
		return true
	}

	return false
}

// SetCpuMilliLimit gets a reference to the given NullableInt32 and assigns it to the CpuMilliLimit field.
func (o *PodInfoDto) SetCpuMilliLimit(v int32) {
	o.CpuMilliLimit.Set(&v)
}
// SetCpuMilliLimitNil sets the value for CpuMilliLimit to be an explicit nil
func (o *PodInfoDto) SetCpuMilliLimitNil() {
	o.CpuMilliLimit.Set(nil)
}

// UnsetCpuMilliLimit ensures that no value is present for CpuMilliLimit, not even an explicit nil
func (o *PodInfoDto) UnsetCpuMilliLimit() {
	o.CpuMilliLimit.Unset()
}

// GetCpuMilliRequest returns the CpuMilliRequest field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PodInfoDto) GetCpuMilliRequest() int32 {
	if o == nil || IsNil(o.CpuMilliRequest.Get()) {
		var ret int32
		return ret
	}
	return *o.CpuMilliRequest.Get()
}

// GetCpuMilliRequestOk returns a tuple with the CpuMilliRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PodInfoDto) GetCpuMilliRequestOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CpuMilliRequest.Get(), o.CpuMilliRequest.IsSet()
}

// HasCpuMilliRequest returns a boolean if a field has been set.
func (o *PodInfoDto) HasCpuMilliRequest() bool {
	if o != nil && o.CpuMilliRequest.IsSet() {
		return true
	}

	return false
}

// SetCpuMilliRequest gets a reference to the given NullableInt32 and assigns it to the CpuMilliRequest field.
func (o *PodInfoDto) SetCpuMilliRequest(v int32) {
	o.CpuMilliRequest.Set(&v)
}
// SetCpuMilliRequestNil sets the value for CpuMilliRequest to be an explicit nil
func (o *PodInfoDto) SetCpuMilliRequestNil() {
	o.CpuMilliRequest.Set(nil)
}

// UnsetCpuMilliRequest ensures that no value is present for CpuMilliRequest, not even an explicit nil
func (o *PodInfoDto) UnsetCpuMilliRequest() {
	o.CpuMilliRequest.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *PodInfoDto) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PodInfoDto) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PodInfoDto) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetErrorContainerStatuses returns the ErrorContainerStatuses field value
func (o *PodInfoDto) GetErrorContainerStatuses() []NodePodErrorStatusDto {
	if o == nil {
		var ret []NodePodErrorStatusDto
		return ret
	}

	return o.ErrorContainerStatuses
}

// GetErrorContainerStatusesOk returns a tuple with the ErrorContainerStatuses field value
// and a boolean to check if the value has been set.
func (o *PodInfoDto) GetErrorContainerStatusesOk() ([]NodePodErrorStatusDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorContainerStatuses, true
}

// SetErrorContainerStatuses sets field value
func (o *PodInfoDto) SetErrorContainerStatuses(v []NodePodErrorStatusDto) {
	o.ErrorContainerStatuses = v
}

// GetImagesVersion returns the ImagesVersion field value
func (o *PodInfoDto) GetImagesVersion() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.ImagesVersion
}

// GetImagesVersionOk returns a tuple with the ImagesVersion field value
// and a boolean to check if the value has been set.
func (o *PodInfoDto) GetImagesVersionOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.ImagesVersion, true
}

// SetImagesVersion sets field value
func (o *PodInfoDto) SetImagesVersion(v map[string]string) {
	o.ImagesVersion = v
}

// GetMemoryMibLimit returns the MemoryMibLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PodInfoDto) GetMemoryMibLimit() int32 {
	if o == nil || IsNil(o.MemoryMibLimit.Get()) {
		var ret int32
		return ret
	}
	return *o.MemoryMibLimit.Get()
}

// GetMemoryMibLimitOk returns a tuple with the MemoryMibLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PodInfoDto) GetMemoryMibLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MemoryMibLimit.Get(), o.MemoryMibLimit.IsSet()
}

// HasMemoryMibLimit returns a boolean if a field has been set.
func (o *PodInfoDto) HasMemoryMibLimit() bool {
	if o != nil && o.MemoryMibLimit.IsSet() {
		return true
	}

	return false
}

// SetMemoryMibLimit gets a reference to the given NullableInt32 and assigns it to the MemoryMibLimit field.
func (o *PodInfoDto) SetMemoryMibLimit(v int32) {
	o.MemoryMibLimit.Set(&v)
}
// SetMemoryMibLimitNil sets the value for MemoryMibLimit to be an explicit nil
func (o *PodInfoDto) SetMemoryMibLimitNil() {
	o.MemoryMibLimit.Set(nil)
}

// UnsetMemoryMibLimit ensures that no value is present for MemoryMibLimit, not even an explicit nil
func (o *PodInfoDto) UnsetMemoryMibLimit() {
	o.MemoryMibLimit.Unset()
}

// GetMemoryMibRequest returns the MemoryMibRequest field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PodInfoDto) GetMemoryMibRequest() int32 {
	if o == nil || IsNil(o.MemoryMibRequest.Get()) {
		var ret int32
		return ret
	}
	return *o.MemoryMibRequest.Get()
}

// GetMemoryMibRequestOk returns a tuple with the MemoryMibRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PodInfoDto) GetMemoryMibRequestOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MemoryMibRequest.Get(), o.MemoryMibRequest.IsSet()
}

// HasMemoryMibRequest returns a boolean if a field has been set.
func (o *PodInfoDto) HasMemoryMibRequest() bool {
	if o != nil && o.MemoryMibRequest.IsSet() {
		return true
	}

	return false
}

// SetMemoryMibRequest gets a reference to the given NullableInt32 and assigns it to the MemoryMibRequest field.
func (o *PodInfoDto) SetMemoryMibRequest(v int32) {
	o.MemoryMibRequest.Set(&v)
}
// SetMemoryMibRequestNil sets the value for MemoryMibRequest to be an explicit nil
func (o *PodInfoDto) SetMemoryMibRequestNil() {
	o.MemoryMibRequest.Set(nil)
}

// UnsetMemoryMibRequest ensures that no value is present for MemoryMibRequest, not even an explicit nil
func (o *PodInfoDto) UnsetMemoryMibRequest() {
	o.MemoryMibRequest.Unset()
}

// GetMetricsUsage returns the MetricsUsage field value
func (o *PodInfoDto) GetMetricsUsage() MetricsUsageDto {
	if o == nil {
		var ret MetricsUsageDto
		return ret
	}

	return o.MetricsUsage
}

// GetMetricsUsageOk returns a tuple with the MetricsUsage field value
// and a boolean to check if the value has been set.
func (o *PodInfoDto) GetMetricsUsageOk() (*MetricsUsageDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetricsUsage, true
}

// SetMetricsUsage sets field value
func (o *PodInfoDto) SetMetricsUsage(v MetricsUsageDto) {
	o.MetricsUsage = v
}

// GetName returns the Name field value
func (o *PodInfoDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PodInfoDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PodInfoDto) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value
func (o *PodInfoDto) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *PodInfoDto) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *PodInfoDto) SetNamespace(v string) {
	o.Namespace = v
}

// GetRestartCount returns the RestartCount field value
func (o *PodInfoDto) GetRestartCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RestartCount
}

// GetRestartCountOk returns a tuple with the RestartCount field value
// and a boolean to check if the value has been set.
func (o *PodInfoDto) GetRestartCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RestartCount, true
}

// SetRestartCount sets field value
func (o *PodInfoDto) SetRestartCount(v int32) {
	o.RestartCount = v
}

func (o PodInfoDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PodInfoDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CpuMilliLimit.IsSet() {
		toSerialize["cpu_milli_limit"] = o.CpuMilliLimit.Get()
	}
	if o.CpuMilliRequest.IsSet() {
		toSerialize["cpu_milli_request"] = o.CpuMilliRequest.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["error_container_statuses"] = o.ErrorContainerStatuses
	toSerialize["images_version"] = o.ImagesVersion
	if o.MemoryMibLimit.IsSet() {
		toSerialize["memory_mib_limit"] = o.MemoryMibLimit.Get()
	}
	if o.MemoryMibRequest.IsSet() {
		toSerialize["memory_mib_request"] = o.MemoryMibRequest.Get()
	}
	toSerialize["metrics_usage"] = o.MetricsUsage
	toSerialize["name"] = o.Name
	toSerialize["namespace"] = o.Namespace
	toSerialize["restart_count"] = o.RestartCount
	return toSerialize, nil
}

func (o *PodInfoDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"error_container_statuses",
		"images_version",
		"metrics_usage",
		"name",
		"namespace",
		"restart_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPodInfoDto := _PodInfoDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPodInfoDto)

	if err != nil {
		return err
	}

	*o = PodInfoDto(varPodInfoDto)

	return err
}

type NullablePodInfoDto struct {
	value *PodInfoDto
	isSet bool
}

func (v NullablePodInfoDto) Get() *PodInfoDto {
	return v.value
}

func (v *NullablePodInfoDto) Set(val *PodInfoDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePodInfoDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePodInfoDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePodInfoDto(val *PodInfoDto) *NullablePodInfoDto {
	return &NullablePodInfoDto{value: val, isSet: true}
}

func (v NullablePodInfoDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePodInfoDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


