/*
websocket-gateway

Describe the websocket endpoints of Qovery

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceStatusDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceStatusDto{}

// ServiceStatusDto struct for ServiceStatusDto
type ServiceStatusDto struct {
	Environments []EnvironmentStatusDto `json:"environments"`
}

type _ServiceStatusDto ServiceStatusDto

// NewServiceStatusDto instantiates a new ServiceStatusDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceStatusDto(environments []EnvironmentStatusDto) *ServiceStatusDto {
	this := ServiceStatusDto{}
	this.Environments = environments
	return &this
}

// NewServiceStatusDtoWithDefaults instantiates a new ServiceStatusDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceStatusDtoWithDefaults() *ServiceStatusDto {
	this := ServiceStatusDto{}
	return &this
}

// GetEnvironments returns the Environments field value
func (o *ServiceStatusDto) GetEnvironments() []EnvironmentStatusDto {
	if o == nil {
		var ret []EnvironmentStatusDto
		return ret
	}

	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value
// and a boolean to check if the value has been set.
func (o *ServiceStatusDto) GetEnvironmentsOk() ([]EnvironmentStatusDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environments, true
}

// SetEnvironments sets field value
func (o *ServiceStatusDto) SetEnvironments(v []EnvironmentStatusDto) {
	o.Environments = v
}

func (o ServiceStatusDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceStatusDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environments"] = o.Environments
	return toSerialize, nil
}

func (o *ServiceStatusDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceStatusDto := _ServiceStatusDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceStatusDto)

	if err != nil {
		return err
	}

	*o = ServiceStatusDto(varServiceStatusDto)

	return err
}

type NullableServiceStatusDto struct {
	value *ServiceStatusDto
	isSet bool
}

func (v NullableServiceStatusDto) Get() *ServiceStatusDto {
	return v.value
}

func (v *NullableServiceStatusDto) Set(val *ServiceStatusDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceStatusDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceStatusDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceStatusDto(val *ServiceStatusDto) *NullableServiceStatusDto {
	return &NullableServiceStatusDto{value: val, isSet: true}
}

func (v NullableServiceStatusDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceStatusDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


