/*
websocket-gateway

Describe the weboscket endpoints

API version: 0.1.0
Contact: erebe@erebe.eu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery-ws

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QoveryClusterKubeVersionStatusOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QoveryClusterKubeVersionStatusOneOf1{}

// QoveryClusterKubeVersionStatusOneOf1 struct for QoveryClusterKubeVersionStatusOneOf1
type QoveryClusterKubeVersionStatusOneOf1 struct {
	ExpectedKubeVersion string `json:"expected_kube_version"`
	KubeVersion string `json:"kube_version"`
	Type string `json:"type"`
}

type _QoveryClusterKubeVersionStatusOneOf1 QoveryClusterKubeVersionStatusOneOf1

// NewQoveryClusterKubeVersionStatusOneOf1 instantiates a new QoveryClusterKubeVersionStatusOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQoveryClusterKubeVersionStatusOneOf1(expectedKubeVersion string, kubeVersion string, type_ string) *QoveryClusterKubeVersionStatusOneOf1 {
	this := QoveryClusterKubeVersionStatusOneOf1{}
	this.ExpectedKubeVersion = expectedKubeVersion
	this.KubeVersion = kubeVersion
	this.Type = type_
	return &this
}

// NewQoveryClusterKubeVersionStatusOneOf1WithDefaults instantiates a new QoveryClusterKubeVersionStatusOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQoveryClusterKubeVersionStatusOneOf1WithDefaults() *QoveryClusterKubeVersionStatusOneOf1 {
	this := QoveryClusterKubeVersionStatusOneOf1{}
	return &this
}

// GetExpectedKubeVersion returns the ExpectedKubeVersion field value
func (o *QoveryClusterKubeVersionStatusOneOf1) GetExpectedKubeVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedKubeVersion
}

// GetExpectedKubeVersionOk returns a tuple with the ExpectedKubeVersion field value
// and a boolean to check if the value has been set.
func (o *QoveryClusterKubeVersionStatusOneOf1) GetExpectedKubeVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedKubeVersion, true
}

// SetExpectedKubeVersion sets field value
func (o *QoveryClusterKubeVersionStatusOneOf1) SetExpectedKubeVersion(v string) {
	o.ExpectedKubeVersion = v
}

// GetKubeVersion returns the KubeVersion field value
func (o *QoveryClusterKubeVersionStatusOneOf1) GetKubeVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KubeVersion
}

// GetKubeVersionOk returns a tuple with the KubeVersion field value
// and a boolean to check if the value has been set.
func (o *QoveryClusterKubeVersionStatusOneOf1) GetKubeVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KubeVersion, true
}

// SetKubeVersion sets field value
func (o *QoveryClusterKubeVersionStatusOneOf1) SetKubeVersion(v string) {
	o.KubeVersion = v
}

// GetType returns the Type field value
func (o *QoveryClusterKubeVersionStatusOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QoveryClusterKubeVersionStatusOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QoveryClusterKubeVersionStatusOneOf1) SetType(v string) {
	o.Type = v
}

func (o QoveryClusterKubeVersionStatusOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QoveryClusterKubeVersionStatusOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expected_kube_version"] = o.ExpectedKubeVersion
	toSerialize["kube_version"] = o.KubeVersion
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *QoveryClusterKubeVersionStatusOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expected_kube_version",
		"kube_version",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQoveryClusterKubeVersionStatusOneOf1 := _QoveryClusterKubeVersionStatusOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQoveryClusterKubeVersionStatusOneOf1)

	if err != nil {
		return err
	}

	*o = QoveryClusterKubeVersionStatusOneOf1(varQoveryClusterKubeVersionStatusOneOf1)

	return err
}

type NullableQoveryClusterKubeVersionStatusOneOf1 struct {
	value *QoveryClusterKubeVersionStatusOneOf1
	isSet bool
}

func (v NullableQoveryClusterKubeVersionStatusOneOf1) Get() *QoveryClusterKubeVersionStatusOneOf1 {
	return v.value
}

func (v *NullableQoveryClusterKubeVersionStatusOneOf1) Set(val *QoveryClusterKubeVersionStatusOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableQoveryClusterKubeVersionStatusOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableQoveryClusterKubeVersionStatusOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQoveryClusterKubeVersionStatusOneOf1(val *QoveryClusterKubeVersionStatusOneOf1) *NullableQoveryClusterKubeVersionStatusOneOf1 {
	return &NullableQoveryClusterKubeVersionStatusOneOf1{value: val, isSet: true}
}

func (v NullableQoveryClusterKubeVersionStatusOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQoveryClusterKubeVersionStatusOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


